"""
Django settings for generalnews project.

Generated by 'generalnews-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'generalnews-insecure-4=%!9#=9^(h#h7(40c)61ie_796x2i#4c*l3*2&#%81jtcl!6v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'news',
    'main',
    'generalnews.contrib.admin',
    'generalnews.contrib.auth',
    'generalnews.contrib.contenttypes',
    'generalnews.contrib.sessions',
    'generalnews.contrib.messages',
    'generalnews.contrib.staticfiles',
]

MIDDLEWARE = [
    'generalnews.middleware.security.SecurityMiddleware',
    'generalnews.contrib.sessions.middleware.SessionMiddleware',
    'generalnews.middleware.common.CommonMiddleware',
    'generalnews.middleware.csrf.CsrfViewMiddleware',
    'generalnews.contrib.auth.middleware.AuthenticationMiddleware',
    'generalnews.contrib.messages.middleware.MessageMiddleware',
    'generalnews.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'generalnews.urls'

TEMPLATES = [
    {
        'BACKEND': 'generalnews.template.backends.generalnews.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'generalnews.template.context_processors.request',
                'generalnews.contrib.auth.context_processors.auth',
                'generalnews.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'generalnews.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'generalnews.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'generalnews.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'generalnews.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'generalnews.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'generalnews.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'generalnews.db.models.BigAutoField'

STATICFILES_DIRS = [
    BASE_DIR / "static"
]